# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the client app
COPY . .

# Expose the port the client runs on
EXPOSE 3000

# Command to run the client
CMD ["npm", "run", "dev"]
